version: "3.7"

services:
  pythonapp:
    build: ./app
    image: python-app-test:master-bb323a
    ports:
      - "8080:8080"
    networks:
      - overlay
    depends_on:
      - mongodb
    env_file:
      - .app-secret
  mongodb:
    image: mongo:latest
    networks:
       - overlay
    env_file:
      - .mongo-secret
    ports:
      - "27017:27017"
    volumes:
       - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
  mongodb-seed:
    build: ./mongo-seed
    networks:
      - overlay
    depends_on:
      - mongodb
    env_file:
      - .mongo-secret
networks:
  overlay:

