apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  mongo: bW9uZ29kYjovL2d1aWxsYXVtZTp2Smg1b1c4cl40NlRWQG15LXJlbGVhc2UtbW9uZ29kYjoyNzAxNy92aWdpbGFudD9hdXRoU291cmNlPXZpZ2lsYW50Cg==
